### ISSUE TITLE
[2.1.8] Error reading from pyproject.toml: No such file

### ISSUE THREAD

**Issue by MikaHD666** [phoenixthrush/AniWorld-Downloader#18]
Steps to replicate:
1. Download Aniworld using the .whl file from the newest release
2. Search for an Anime using the interactive menu

`2024-10-27 19:08:01 - ERROR - get_version_from_pyproject - Error reading version from pyproject.toml: [Errno 2] No such file or directory: 'C:\\Users\\mikah\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\aniworld\\common\\../../../pyproject.toml'`

**Comment by MikaHD666** [comment]
You're actually the fastest person i've ever seen on GitHub!
Fixed with commit a0ad947

**Comment by phoenixthrush** [comment]
Hi Mika,
sorry it doesn't work yet, I haven't fixed it yet.

**Comment by MikaHD666** [comment]
I didn't realize it was an issue with the whl file. When i saw the commit i git cloned, tried it and it worked.

**Comment by phoenixthrush** [comment]
Hi Mika,
I've fixed the version bug, and the coming .whl files should work now.
Still, I'd recommend using pip install aniworld to install it directly from PyPI.
