### ISSUE TITLE
Failing to echo special characters like "&"

### ISSUE THREAD

**Issue by MikaHD666** [phoenixthrush/AniWorld-Downloader#21]
I came across this error when trying to download an anime with the "&" character in the title.

Succesfully Downloaded File to 'C:\Users\mikah\Downloads\Love Chunibyo Other Delusions\Love, Chunibyo & Other Delusions - S1E1.mp4'
2024-10-31 18:12:57 - CRITICAL - execute_command - Command 'cmd /c echo Downloading to 'C:\Users\mikah\Downloads\Love Chunibyo Other Delusions\Love, Chunibyo & Other Delusions - S1E1.mp4'' returned non-zero exit status 1.

**Comment by phoenixthrush** [comment]
Hi Mika,
thanks for telling, yes that definitely needs to be fixed by sanitising the string before echoing it out.

**Comment by MikaHD666** [comment]
After some further analysis i figured out that the error is coming from the spaces in the directory name
So, _"Love, Chunibyo % Other Delusions"_ is invalid.

Now that i mention, it would be a good idea to let the user specify the output directory including the directory where the final mp4 s end up

**Comment by phoenixthrush** [comment]
The output folder should be named `Love Chunibyo Other Delusions` without any invalid characters anyways.
I'm not able to test if adding `""` around the filename would fix the echo issue.

I’ll also add an option to select the final output directory. Thanks for the suggestion!

**Comment by phoenixthrush** [comment]
Could you try running it again using the latest commit?

**Comment by phoenixthrush** [comment]
I’ll test this on Windows tomorrow to see if it works.
It already does on macOS and likely Linux.

**Comment by MikaHD666** [comment]
Works on my end with the newest commit!
