### ISSUE TITLE
DoodStream Support

### ISSUE THREAD

**Issue by Commandcracker** [phoenixthrush/AniWorld-Downloader#25]
You can basically copy this https://github.com/Commandcracker/gucken/blob/main/src/gucken/hoster/doodstream.py you just need to change it so it is using urllib, and you need to pass the Referer header to mpv, yt-dlp etc.

**Comment by phoenixthrush** [comment]
Hi, I will look into it, but I am currently trying to completely rewrite everything, but if you want to implement it, I would really appreciate and love that!
