### ISSUE TITLE
yt-dlp error

### ISSUE THREAD

**Issue by xdSpoty** [phoenixthrush/AniWorld-Downloader#26]
If i just wonna Downlaod One Piece i choose Download my folder wich is in /mnt 

and this error shows for a single sec. 

yt-dlp: error: no such option: --http-header-fields
<img width="854" alt="Screenshot 2024-12-11 202352" src="https://github.com/user-attachments/assets/06bec7e0-0d94-4f97-9853-4e8a1c02c425" />

**Comment by YozouChan** [comment]
Hey, i sadly have the same issue :(
Any solutions there?

**Comment by xdSpoty** [comment]
> Hey, i sadly have the same issue :( Any solutions there?

I think we need the same yt-dlp version from the author

**Comment by phoenixthrush** [comment]
Hi, I’m currently away from home and will check in about an hour. For now, could you please install an older version by running `pip install aniworld==2.3.4`?

**Comment by Tmaster055** [comment]
Thanks for reporting the issue! It should now be fixed in the newer versions. Have a nice evening and if you like this project don't forget to star, it would mean the world to us!

**Comment by phoenixthrush** [comment]
Just released v.2.4.1 which should fix the issue for yt-dlp.
Please run `pip install -U aniworld`.
