### ISSUE TITLE
S.to compatibility 

### ISSUE THREAD

**Issue by GamingKatze153** [phoenixthrush/AniWorld-Downloader#5]
Hello my request is to make s.to compatibility because it seems similar to aniworld

**Comment by phoenixthrush** [comment]
Hi,

adding support for S.to is not currently planned. This project is specifically called aniworld and will probably only support aniworld in the future.

There are other projects that already support s.to. Have a look at [https://github.com/wolfswolke/aniworld_scraper](wolfswolke/aniworld_scraper).

If you want to watch from S.to instead, I can recommend [https://github.com/Commandcracker/gucken](Commandcracker/gucken).
