### ISSUE TITLE
Error with German Dub

### ISSUE THREAD

**Issue by Rexidexi** [phoenixthrush/AniWorld-Downloader#6]
When trying to download a german dub using the following line: "aniworld --episode https://aniworld.to/anime/stream/one-piece/staffel-1/episode-1 --keep-watching --action Download --provider VOE --language German Dub"  the error "aniworld: error: argument --language: invalid choice: 'German' (choose from 'German Dub', 'English Sub', 'German Sub')" comes up.

**Comment by Rexidexi** [comment]
missed the " at the start and end of German Dub"

**Comment by phoenixthrush** [comment]
Hi,

thanks for pointing this out!

I'll add an example to the README to make it clearer for others.

Also, if you're enjoying the project, a star on GitHub would really make my day!
